// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductInventory.Models;

#nullable disable

namespace ProductInventory.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260911163145_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductInventory.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 9, 11, 10, 31, 43, 999, DateTimeKind.Local).AddTicks(9437));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 9, 11, 10, 31, 44, 0, DateTimeKind.Local).AddTicks(149),
                            Description = "High-performance laptop",
                            Name = "Laptop",
                            Price = 999.99m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 9, 11, 10, 31, 44, 0, DateTimeKind.Local).AddTicks(152),
                            Description = "Wireless mouse",
                            Name = "Mouse",
                            Price = 29.99m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 9, 11, 10, 31, 44, 0, DateTimeKind.Local).AddTicks(156),
                            Description = "Mechanical keyboard",
                            Name = "Keyboard",
                            Price = 89.99m,
                            Quantity = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
