name: Build ProductInventory

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
         run: dotnet restore ProductInventory.slnx

      - name: Build
        run: dotnet build ProductInventory.slnx --configuration Release --no-restore

        - name: Test
        run: dotnet test ProductInventory.slnx --configuration Release --no-build
